import { StyleSheet } from "react-native";

export const styles = StyleSheet.create({
  container: {
    padding: 16,
    paddingBottom: 24,
    backgroundColor: "#F5F6FA",
    gap: 16,
  },
  header: {
    gap: 6,
  },
  title: {
    fontSize: 22,
    fontWeight: "800",
    color: "#111827",
  },
  subtitle: {
    fontSize: 13,
    color: "#6B7280",
    lineHeight: 18,
  },
  section: {
    borderRadius: 14,
    padding: 14,
    backgroundColor: "#FFFFFF",
    borderWidth: 1,
    borderColor: "#E5E7EB",
    gap: 10,
  },
  sectionTitle: {
    fontSize: 16,
    fontWeight: "700",
    color: "#111827",
  },
  sectionHint: {
    fontSize: 12,
    color: "#6B7280",
  },
  fieldLabel: {
    marginTop: 6,
    marginBottom: 4,
    fontSize: 13,
    fontWeight: "600",
    color: "#374151",
  },
  floorList: {
    gap: 8,
    marginVertical: 2,
  },
  floorChip: {
    paddingVertical: 8,
    paddingHorizontal: 14,
    borderRadius: 999,
    borderWidth: 1,
    borderColor: "#D1D5DB",
    backgroundColor: "#FFFFFF",
  },
  floorChipSelected: {
    backgroundColor: "#1D4ED8",
    borderColor: "#1D4ED8",
  },
  floorChipText: {
    fontSize: 13,
    fontWeight: "600",
    color: "#111827",
  },
  floorChipTextSelected: {
    color: "#FFFFFF",
  },
  roomSelector: {
    borderWidth: 1,
    borderRadius: 12,
    borderColor: "#D1D5DB",
    padding: 12,
    flexDirection: "row",
    justifyContent: "space-between",
    alignItems: "center",
    backgroundColor: "#F9FAFB",
  },
  roomSelectorText: {
    flex: 1,
    paddingRight: 10,
  },
  roomCode: {
    fontWeight: "600",
    color: "#111827",
  },
  roomName: {
    marginTop: 2,
    fontSize: 12,
    color: "#6B7280",
  },
  chevron: {
    fontSize: 18,
    color: "#9CA3AF",
  },
  uploadButton: {
    marginTop: 4,
    paddingVertical: 10,
    paddingHorizontal: 12,
    borderRadius: 10,
    borderWidth: 1,
    borderColor: "#D1D5DB",
    backgroundColor: "#F9FAFB",
    alignItems: "center",
  },
  uploadButtonText: {
    fontWeight: "600",
    color: "#111827",
  },
  previewImage: {
    width: "100%",
    height: 200,
    borderRadius: 12,
    marginTop: 10,
  },
  textArea: {
    minHeight: 110,
    borderWidth: 1,
    borderRadius: 10,
    borderColor: "#D1D5DB",
    padding: 12,
    textAlignVertical: "top",
    backgroundColor: "#F9FAFB",
    fontSize: 13,
  },
  evidenceStatus: {
    marginTop: 6,
    fontSize: 12,
  },
  evidenceOk: {
    color: "#16A34A",
  },
  evidenceMissing: {
    color: "#F97316",
  },
  submitButton: {
    marginTop: 4,
    paddingVertical: 14,
    borderRadius: 999,
    backgroundColor: "#1D4ED8",
    alignItems: "center",
  },
  submitButtonDisabled: {
    backgroundColor: "#93C5FD",
  },
  submitButtonText: {
    fontSize: 16,
    fontWeight: "700",
    color: "#FFFFFF",
  },
  modalBackdrop: {
    flex: 1,
    backgroundColor: "rgba(0,0,0,0.25)",
    justifyContent: "flex-end",
  },
  modalSheet: {
    backgroundColor: "#FFFFFF",
    borderTopLeftRadius: 16,
    borderTopRightRadius: 16,
    padding: 14,
    maxHeight: "75%",
    borderWidth: 1,
    borderColor: "#E5E7EB",
  },
  modalHeader: {
    flexDirection: "row",
    justifyContent: "space-between",
    alignItems: "center",
    paddingBottom: 8,
  },
  modalTitle: {
    fontSize: 16,
    fontWeight: "700",
    color: "#111827",
  },
  modalClose: {
    fontSize: 14,
    fontWeight: "600",
    color: "#4B5563",
  },
  searchInput: {
    borderWidth: 1,
    borderColor: "#D1D5DB",
    borderRadius: 10,
    paddingHorizontal: 12,
    paddingVertical: 10,
    marginBottom: 12,
    backgroundColor: "#F9FAFB",
    fontSize: 13,
  },
  emptySearchText: {
    textAlign: "center",
    color: "#6B7280",
    fontSize: 13,
    marginTop: 12,
  },
  roomOption: {
    paddingVertical: 10,
    paddingHorizontal: 10,
    borderRadius: 10,
    borderWidth: 1,
    borderColor: "#E5E7EB",
    marginBottom: 8,
    backgroundColor: "#F9FAFB",
  },
  roomOptionCode: {
    fontWeight: "700",
    color: "#111827",
  },
  roomOptionName: {
    marginTop: 2,
    fontSize: 12,
    color: "#6B7280",
  },
  locationBanner: {
    borderRadius: 12,
    padding: 10,
    marginBottom: 8,
  },
  locationBannerHeader: {
    flexDirection: "row",
    alignItems: "center",
    justifyContent: "space-between",
    gap: 12,
    marginBottom: 4,
  },
  locationBannerTitle: {
    fontSize: 13,
    fontWeight: "700",
    flex: 1,
  },
  locationBannerText: {
    fontSize: 12,
    color: "#374151",
    lineHeight: 16,
  },
  refreshLocationButton: {
    borderRadius: 999,
    paddingHorizontal: 10,
    paddingVertical: 6,
    backgroundColor: "#FFFFFF",
    borderWidth: 1,
    borderColor: "#D1D5DB",
  },
  refreshLocationButtonDisabled: {
    opacity: 0.6,
  },
  refreshLocationButtonText: {
    fontSize: 12,
    fontWeight: "600",
    color: "#111827",
  },
});
